// ui/src/App.tsx
import React from "react";
import Button from "@mui/material/Button";
import {createDockerDesktopClient} from "@docker/extension-api-client";
import {Grid, Stack, TextField, Typography} from "@mui/material";
import {
    checkK8sConnection,
    primeCluster,
    getToken,
    portForward,
    deprimeCluster,
} from "./helper/kubernetes";

import {
    listHelmReleases,
    installKubernetesDashboardChart,
    uninstallKubernetesDashboardChart,
} from "./helper/helm";

// Note: This line relies on Docker Desktop's presence as a host application.
// If you're running this React app in a browser, it won't work properly.
const client = createDockerDesktopClient();

function useDockerDesktopClient() {
    return client;
}

export function App() {
    const [response, setResponse] = React.useState<string | undefined>();
    const ddClient = useDockerDesktopClient();

    async function loadKubernetesDashboard() {
        window.location.href = "http://localhost:3000";
    }

    return (
        <>
            <Typography variant="h3">Kuberntes Dashboard Extension</Typography>
            <Typography variant="body1" color="text.secondary" sx={{mt: 2}}>
                Prime cluster for Kubernetes Dashboard.
                Install Kubernetes Dashboard Helm chart.
                Forward port.
                Get token.
                Load Kubernetes Dashboard.
                Optionally, uninstall Kubernetes Dashboard Helm release.
            </Typography>
            <Grid container spacing={2}>
                <Grid item>
                    <Stack direction="row" alignItems="start" spacing={2} sx={{mt: 4}}>
                        <Button
                            color="info"
                            variant="contained"
                            onClick={async () => {
                                const result = await checkK8sConnection(ddClient);
                                setResponse(result);
                            }}
                        >
                            Check connection to Cluster
                        </Button>
                        <Button
                            color="info"
                            variant="contained"
                            onClick={async () => {
                                const result = await listHelmReleases(ddClient);
                                setResponse(result as string);
                            }}
                        >
                            List Kubernetes Dashboard Helm Release
                        </Button>
                    </Stack>
                    <Stack direction="row" alignItems="start" spacing={2} sx={{mt: 4}}>
                        <Button
                            variant="contained"
                            onClick={async () => {
                                const result = await primeCluster(ddClient);
                                setResponse(result);
                            }}
                        >
                            Step 1: Prime cluster
                        </Button>
                        <Button
                            variant="contained"
                            onClick={async () => {
                                const result = await installKubernetesDashboardChart(ddClient);
                                setResponse(result as string);
                            }}
                        >
                            Step 2: Install kubernetes dashboard chart
                        </Button>

                        <Button
                            variant="contained"
                            onClick={async () => {
                                await portForward(ddClient);
                                setResponse('Port Forwarding started');
                            }}
                        >
                            Step 3: Port Forward
                        </Button>

                        <Button
                            variant="contained"
                            onClick={async () => {
                                const result = await getToken(ddClient);
                                setResponse(result as string);
                                navigator.clipboard.writeText(result);
                            }}
                        >
                            Step 4: Get Token
                        </Button>

                        <Button
                            variant="contained"
                            onClick={async () => {
                                const result = await loadKubernetesDashboard();
                            }}
                        >
                            Step 5: Load Kubernetes Dashboard
                        </Button>
                    </Stack>
                </Grid>
                <Grid item>
                    <TextField
                        sx={{width: '94vw'}}
                        disabled
                        multiline
                        variant="outlined"
                        minRows={20}
                        value={response ?? ""}
                    />
                </Grid>
                <Grid item>
                    <Stack direction="row" alignItems="start" spacing={2} sx={{mt: 4}}>
                        <Button
                            color="error"
                            variant="contained"
                            onClick={async () => {
                                const result = await uninstallKubernetesDashboardChart(ddClient);
                                setResponse(result as string);
                            }}
                        >
                            Cleanup Step 1: Uninstall Kubernetes Dashboard
                        </Button>

                        <Button
                            color="error"
                            variant="contained"
                            onClick={async () => {
                                const result = await deprimeCluster(ddClient);
                                setResponse(result);
                            }}
                        >
                            Cleanup Step 2: Deprime cluster
                        </Button>
                    </Stack>
                </Grid>
            </Grid>
        </>
    );
}

// ui/src/app/app.component.ts
import {Component} from '@angular/core';
import {FormsModule} from '@angular/forms';
import {RouterOutlet} from '@angular/router';
import {createDockerDesktopClient} from "@docker/extension-api-client";

import {
  checkK8sConnection,
  primeCluster,
  getToken,
  portForward,
  deprimeCluster,
} from "./helper/kubernetes";

import {
  listHelmReleases,
  installKubernetesDashboardChart,
  uninstallKubernetesDashboardChart,
} from "./helper/helm";

@Component({
  selector: 'app-root',
  standalone: true,
  imports: [RouterOutlet, FormsModule],
  templateUrl: './app.component.html',
  styleUrl: './app.component.scss'
})
export class AppComponent {
  private _output: string | undefined;
  private ddClient = createDockerDesktopClient();

  constructor() {
    this._output = "";
  }

  async checkK8sConnection() {
    this.output = await checkK8sConnection(this.ddClient);
  }

  async listHelmReleases() {
    this.output = await listHelmReleases(this.ddClient);
  }

  async primeCluster() {
    this.output = await primeCluster(this.ddClient);
  }

  async installKubernetesDashboardChart() {
    this.output = await installKubernetesDashboardChart(this.ddClient);
  }

  async portForward() {
    this.output = await portForward(this.ddClient);
  }

  async getToken() {
    this.output = await getToken(this.ddClient);
    navigator.clipboard.writeText(this.output);
  }

  loadKubernetesDashboard() {
    window.location.href = "http://localhost:3000";
  }

  async uninstallKubernetesDashboardChart() {
    this.output = await uninstallKubernetesDashboardChart(this.ddClient);
  }

  async deprimeCluster() {
    this.output = await deprimeCluster(this.ddClient);
  }

  set output(commandOutput: string | undefined) {
    this._output = commandOutput;
  }

  get output() {
    return this._output;
  }

}

<div class="mr-auto grid gap-y-2 content-start justify-items-start items-start content-start max-w-[99vw] h-screen">
  <div class="flex p-2 gap-x-2 bg-gray-50 border rounded-md w-full">
    <button class="py-2 px-4 border rounded-md" (click)="primeCluster()">Step 1: Prime Cluster</button>
    <button class="py-2 px-4 border rounded-md" (click)="installKubernetesDashboardChart()">Step 2: Install Kubernetes Dashboard Chart</button>
    <button class="ml-auto py-2 px-4 border rounded-md" (click)="portForward()">Step 3: Port Forward</button>
    <button class="py-2 px-4 border rounded-md" (click)="getToken()">Step 4: Get Token</button>
    <button class="py-2 px-4 border rounded-md bg-green-200" (click)="loadKubernetesDashboard()">Step 5: Load Kubernetes Dashboard</button>
  </div>
  <pre class="p-2 border rounded-md text-sm min-w-[99vw] max-w-[99vw] w-[99vw] overflow-x-scroll min-h-[20rem]" [innerText]="output"></pre>
  <div class="flex p-2 px-2 gap-x-2 bg-gray-50 border rounded-md w-full">
    <button class="py-2 px-4 border rounded-md" (click)="checkK8sConnection()">Check connection to cluster</button>
    <button class="py-2 px-4 border rounded-md" (click)="listHelmReleases()">List Kubernetes Dashboard Release</button>
    <button class="ml-auto py-2 px-4 border rounded-md bg-red-200" (click)="uninstallKubernetesDashboardChart()">Cleanup Step 1: Uninstall Kubernetes Dashboard Chart</button>
    <button class="py-2 px-4 border rounded-md bg-red-200" (click)="deprimeCluster()">Cleanup Step 2: Deprime Cluster</button>
  </div>
</div>
